AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudFormation template for creating S3 bucket with Block Public Access settings'
Parameters:
  S3BucketName:
    Type: String
  AWSRegion:
    Type: String
    AllowedValues:
      - us-east-1
      - us-west-2
      - us-east-2
      - ap-south-1
      - eu-north-1
  BucketVersioning:
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
  ObjectOwnership:
    Type: String
    AllowedValues:
      - ACLsdisabled
      - ACLsenabled
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: !Ref BucketVersioning
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
